import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { MoralisProvider } from 'react-moralis'
import styles from '../styles/Home.module.css'
import { contract as contractAddress } from '../contractAddress';
import MetamaskLogin from "../components/MetamaskLogin/MetamaskLogin";
import FeatureToggle from '../abis/FeatureToggle.json';
const APP_ID = process.env.NEXT_PUBLIC_APP_ID ?? '';
const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL ?? '';

const Home: NextPage = () => {
    const getUserAddress = async () => {
        const web3 = await Moralis.Web3.enableWeb3()
        const accounts = await web3.eth.getAccounts()
        return accounts[0] as string;
    };
    const optionsCore = {
        contractAddress: contractAddress,
        abi: FeatureToggle.abi,
    };
    const userAddress = await getUserAddress()

    const getIsEnabledOptions = {
        functionName: "getIsEnabled",
        params: {
            toggleId: 0
        },
        ...optionsCore
    }

    const updateToggleOptions = {
        functionName: "updateToggle",
        params: {
            toggleId: 0,
            isEnabled: true,
            name: "shouldRenderCopy"
        },
        ...optionsCore
    }
    const getIsEnabled = async () => {
        const result = await Moralis.Web3.executeFunction(getIsEnabledOptions)
        console.log('isEnabled for toggleId 0', result);
    }

    const updateToggle = async () => {
        const result = await Moralis.Web3.executeFunction(updateToggleOptions)
        console.log('updatedToggle', result)
    }

  return (
      <MoralisProvider appId={APP_ID} serverUrl={SERVER_URL}>
    <div className={styles.container}>
      <Head>
        <title>Web3 Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            demo page!
        </h1>
        <h1 className={styles.title}>
          <MetamaskLogin/>

        </h1>
        contract deployed to: {contractAddress}



      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
      </MoralisProvider>
  )
}
const App = () => {
  // return(
  //     <MoralisProvider appId={APP_ID} serverUrl={SERVER_URL}>
  //       <MyApp Component={Home} pageProps={null} router={}/>
  //     </MoralisProvider>
  // )
}
export default Home;
